### ISSUE TITLE
i need use two onedrivers for two accounts?

### ISSUE THREAD

**Issue by fengmao31** [jstaf/onedriver#100]
i need use two onedrivers for two accounts?

**Comment by fengmao31** [comment]
systemd
can you give a guide tip about how to use it for two onedrivers

**Comment by drom98** [comment]
It's in the README.
https://github.com/jstaf/onedriver#multiple-drives-and-starting-onedrive-on-login

**Comment by jstaf** [comment]
I'm going to close this - @drom98 is correct in that instructions on doing this are in the readme. Once I get around to finishing it, there will be a GUI to make this process easier.
