### ISSUE TITLE
how to mout work shared library

### ISSUE THREAD

**Issue by jasonblewis** [jstaf/onedriver#101]
I can't work out how to mount my work's shared library. When I run onedriver, it prompts me to log in. After login I see my work personal onedrive but not the shared libraries.

Is there some way to get the shared libraries?

**Comment by jstaf** [comment]
It's on my todo list, but I haven't had a chance to implement it yet (right now onedriver only knows about your user's drive, but not shared items from other drives). You can track this feature getting added here: https://github.com/jstaf/onedriver/issues/70

**Comment by jasonblewis** [comment]
thanks. Closing and I'll follow on #70
