### ISSUE TITLE
Onedriver repository 404 not found

### ISSUE THREAD

**Issue by Agrigohar** [jstaf/onedriver#108]
`Err:11 http://ppa.launchpad.net/jstaf/onedriver/ubuntu bionic Release                  
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
`

**Comment by jstaf** [comment]
Try doing a `sudo apt update` and installing things again.

**Comment by NormanBB** [comment]
> `Err:11 http://ppa.launchpad.net/jstaf/onedriver/ubuntu bionic Release 404 Not Found [IP: 2001:67c:1560:8008::19 80] `

You need to replace bionic with focal.

`This PPA can be added to your system manually by copying the lines below and adding them to your system's software sources.

deb http://ppa.launchpad.net/jstaf/onedriver/ubuntu focal main `

**Comment by jstaf** [comment]
I'm going to leave this open as a reminder to check that packages are being built for `bionic`

**Comment by jstaf** [comment]
Very old issue, but closing this because I don't think `bionic` has ever been supported (onedriver needs Go 1.11+, bionic has 1.10.4). But we do support all of the other current Ubuntu releases and theoretically a flatpak would work on 18.04.
