### ISSUE TITLE
onedriver-headless build failure.

### ISSUE THREAD

**Issue by NormanBB** [jstaf/onedriver#109]
My steps is 

```
1. Download the source sode.
2. make onedriver-headless
3. make install

```

And it also shows `Gtk-WARNING **: cannot open display:`.
Did I done something wrong?

**Comment by jstaf** [comment]
`make onedriver-headless` creates a `onedriver-headless` binary in the current working directory that is not related to the task from `make install`. `make install` is for normal installation unrelated to the headless binary.

**Comment by NormanBB** [comment]
> `make onedriver-headless` creates a `onedriver-headless` binary in the current working directory that is not related to the task from `make install`. `make install` is for normal installation unrelated to the headless binary.
> 
> Just use the `onedriver-headless` binary as you would the `onedriver` one normally created.

Thank you for answer . I now realized that i don't follow README properly .
