### ISSUE TITLE
Having 2 onedrive accounts (business & priv) - no info for which one give credentials when they are periodically required

### ISSUE THREAD

**Issue by siwieck** [jstaf/onedriver#110]
Hi I have 2 onedrive accounts business and private linked in debian to separate folders (crostini chrome os) via onedriver.
This works wery well, up to moments when I need to renew my credentials (required every two week by business accounts and more seldom by private). Then standard microsoft windows popup appears but without information to which accounts / to which folder (private or business) I should renew credentials. If I guess wrongly then I have for example 2 business accounts linked or two private accounts and I have to reset the setup in linux, changing folder name. 

So some information for which folder the credentials are needed would help much. I do not know how to implement it or whether this can be easily implemented, but this would help a lot. 

Anyway thank you very much for onedriver,
Chris

**Comment by jstaf** [comment]
Let me see if I can add the account name to the header of the window on reauth.

**Comment by jstaf** [comment]
Added in #125. The account name is now displayed in the titlebar when re-authenticating (as long as onedriver knows what it is).
