### ISSUE TITLE
I created an AUR package for onedriver

### ISSUE THREAD

**Issue by fmoledina** [jstaf/onedriver#114]
Hello @jstaf 

I created a [onedriver package](https://aur.archlinux.org/packages/onedriver/) in the [Arch User Repository](https://aur.archlinux.org/). My intent is to track tagged releases. I have extracted the key steps from the Makefile and incorporated Arch PKGBUILD guidelines. Also included are `install` line items for the `.desktop` file and icons.

I'd like to propose that in the _Quick Start_ section of the README, I can add the following line just after the Ubuntu/Pop!_OS/Debian instructions:

> Arch/Manjaro/EndeavourOS users can install onedriver from the [AUR](https://aur.archlinux.org/packages/onedriver/).

If that's acceptable, I can submit a quick PR for this. Thanks!

**Comment by jstaf** [comment]
That sounds great, submit the PR! :slightly_smiling_face:
