### ISSUE TITLE
Error with Building on Debian SID on chromeOS (libwebkit2gtk-4.0-dev unable to install)

### ISSUE THREAD

**Issue by dsoundmn** [jstaf/onedriver#117]
Building on Chrome 

dsoundmn@penguin:~/builder/onedriver$ make
go build -ldflags="-X main.commit=cffc51ecb8b464a2aad97fa5144513c3a8d0c96e" ./cmd/onedriver
# pkg-config --cflags  -- webkit2gtk-4.0
Package webkit2gtk-4.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkit2gtk-4.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'webkit2gtk-4.0' found
pkg-config: exit status 1
make: *** [Makefile:22: onedriver] Error 2

Likely that this is due to being unable to install the lib
root@penguin:~# apt-get install libwebkit2gtk-4.0-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libdrm-dev : Depends: libdrm2 (= 2.4.99-1-cros0) but 2.4.104-1 is to be installed
              Depends: libdrm-intel1 (= 2.4.99-1-cros0) but 2.4.104-1 is to be installed
              Depends: libdrm-radeon1 (= 2.4.99-1-cros0) but 2.4.104-1 is to be installed
              Depends: libdrm-nouveau2 (= 2.4.99-1-cros0) but 2.4.104-1 is to be installed
              Depends: libdrm-amdgpu1 (= 2.4.99-1-cros0) but 2.4.104-1 is to be installed
 libegl-dev : Breaks: libegl1-mesa-dev (< 19.3.0~rc6-1) but 19.2.8~cros1 is to be installed
 libgl-dev : Breaks: mesa-common-dev (< 19.3.0~rc6-1) but 19.2.8~cros1 is to be installed
 libglx-dev : Breaks: mesa-common-dev (< 19.3.0~rc6-1) but 19.2.8~cros1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by jstaf** [comment]
Yeah, you'll need to install the webkit2gtk headers for this to work. You can also perform a headless build (see instructions) for a build that doesn't require webkit. The only difference between the two is that the headless binary doesn't have a GUI for authentication (it'll walk you through things on the CLI though).

Also if you're on Debian you can also just install from the Ubuntu PPAs, there's both prebuilt amd64 and arm64 packages depending on your architecture. The package is pretty generic, and should work on all Debian derivatives (it just depends on webkit2gtk and glibc, if I recall correctly).

**Comment by dsoundmn** [comment]
gotcha - seems like a headless build is the best route for Debian Sid on the Chromebook (Sid on chrome OS was much simpler than I expected) even when using the deb package the authentication screen flickers like crazy.
