### ISSUE TITLE
onedriver-launcer on aur

### ISSUE THREAD

**Issue by alexpetrean80** [jstaf/onedriver#135]
could we have the gui on AUR as well?

**Comment by jstaf** [comment]
Of course! I'm not actually the person who maintains the AUR build though, you might need to poke @fmoledina.

FYI there isn't a published version with the GUI yet (still a couple things I want to tweak with it), which what the AUR build works off of. In the meantime if you want to try out the GUI, your best bet is to build off of the current master with `make` + `sudo make install`.

**Comment by fmoledina** [comment]
I could create a `onedriver-git` package in the AUR that builds from master on a reasonable schedule. Let me check it out and report back sometime this coming week. Thanks!

**Comment by fmoledina** [comment]
@alexpetrean80 have a look at the [onedriver-git](https://aur.archlinux.org/packages/onedriver-git/) in the AUR. I did a quick check on a test machine and was able to load up the GUI, but I haven't migrated my main machine to this yet.

**Comment by alexpetrean80** [comment]
@fmoledina thanks man, it works perfectly.
