### ISSUE TITLE
Consistent high CPU usage

### ISSUE THREAD

**Issue by NICHOLAS85** [jstaf/onedriver#138]
**onedriver version**
> onedriver v0.10.1 (via Aur package)

**Used Distribution:**
> Bedrock Linux 0.7.20 Poki, Arch and Debian strata

So I've disabled indexing of the mount however I still find onedriver spiking in CPU usage when not interacted with. Looking at the log it seems It keeps "Serializing cache metadata to disk" every couple of minutes causing increased CPU usage. Is this normal behavior?

<details>
<summary>journalctl -f --user-unit onedriver@home-nicholas-OneDrive.service</summary>

```
...
Jun 15 14:37:11 Nicks-Laptop strat[14114]: time="2021-06-15T14:37:11" level=debug msg="Serializing cache metadata to disk." func="000041:fs.(*Cache).SerializeAll()" file="cache.go:523"
Jun 15 14:39:19 Nicks-Laptop strat[14114]: time="2021-06-15T14:39:19" level=debug msg="Fetching deltas from server." func="000041:fs.(*Cache).DeltaLoop()" file="delta.go:21"
Jun 15 14:39:20 Nicks-Laptop strat[14114]: time="2021-06-15T14:39:20" level=info msg="Fetched 0 deltas." func="000041:fs.(*Cache).DeltaLoop()" file="delta.go:44"
Jun 15 14:39:20 Nicks-Laptop strat[14114]: time="2021-06-15T14:39:20" level=debug msg="Serializing cache metadata to disk." func="000041:fs.(*Cache).SerializeAll()" file="cache.go:523"
Jun 15 14:41:29 Nicks-Laptop strat[14114]: time="2021-06-15T14:41:29" level=debug msg="Fetching deltas from server." func="000041:fs.(*Cache).DeltaLoop()" file="delta.go:21"
Jun 15 14:41:29 Nicks-Laptop strat[14114]: time="2021-06-15T14:41:29" level=info msg="Fetched 0 deltas." func="000041:fs.(*Cache).DeltaLoop()" file="delta.go:44"
Jun 15 14:41:29 Nicks-Laptop strat[14114]: time="2021-06-15T14:41:29" level=debug msg="Serializing cache metadata to disk." func="000041:fs.(*Cache).SerializeAll()" file="cache.go:523"
Jun 15 14:44:47 Nicks-Laptop strat[14114]: time="2021-06-15T14:44:47" level=debug msg="Fetching deltas from server." func="000041:fs.(*Cache).DeltaLoop()" file="delta.go:21"
Jun 15 14:44:48 Nicks-Laptop strat[14114]: time="2021-06-15T14:44:48" level=info msg="Fetched 0 deltas." func="000041:fs.(*Cache).DeltaLoop()" file="delta.go:44"
Jun 15 14:44:48 Nicks-Laptop strat[14114]: time="2021-06-15T14:44:48" level=debug msg="Serializing cache metadata to disk." func="000041:fs.(*Cache).SerializeAll()" file="cache.go:523"
Jun 15 14:47:08 Nicks-Laptop strat[14114]: time="2021-06-15T14:47:08" level=debug msg="Fetching deltas from server." func="000041:fs.(*Cache).DeltaLoop()" file="delta.go:21"
Jun 15 14:47:09 Nicks-Laptop strat[14114]: time="2021-06-15T14:47:09" level=info msg="Fetched 0 deltas." func="000041:fs.(*Cache).DeltaLoop()" file="delta.go:44"
Jun 15 14:47:09 Nicks-Laptop strat[14114]: time="2021-06-15T14:47:09" level=debug msg="Serializing cache metadata to disk." func="000041:fs.(*Cache).SerializeAll()" file="cache.go:523"
```

</details>

**Comment by jstaf** [comment]
Yes, this is normal behavior. Every 30 seconds, the onedriver writes all of the information for files it knows about to disk. Having an up-to-date copy of this information on disk is required to let you start the filesystem when your computer doesn't have internet access and is what allows onedriver to transition from a read-only "offline mode" to the normal "online mode" without a restart (this is especially important if you've set onedriver to start on login via systemd... if using wifi, your user session typically does not have internet for the first few seconds after login).

Despite this, this process can definitely be made more efficient (there's no need to sync everything to disk if everything has already been synced previously... we can just sync outstanding changes). This optimization will probably need to wait for a later date though - I'll confess that my current focus is on fixing any major bugs/adding features. I'll probably revisit performance stuff like this once things are more feature-complete.

**Comment by NICHOLAS85** [comment]
Ahh alright! Looking forward to seeing how this develops, worked much better than rsync alone. Unfortunately, I mainly use a laptop and the high cpu usage would drain it, I'll keep an eye out for your optimization pass and try it out again. Good luck with development till then!

**Comment by NICHOLAS85** [comment]
Just tested out the latest version. Onedriver is now much better on CPU usage than in my previous experience. I'm going to keep it running for a while and see if it has any noticeable effect on battery life.

**Comment by jstaf** [comment]
Sweet - yeah I fixed a really problematic db transaction (its still doing the "sync everything every 30s behavior" but it's a lot more efficient now). There's still more optimization I can do but I think that was the big one.

**Comment by jstaf** [comment]
Going to close this since it seems to be resolved.
