### ISSUE TITLE
Does not (visibly) start

### ISSUE THREAD

**Issue by remcoNL** [jstaf/onedriver#139]
Hi Jstaf,

I've installed onedriver several times now from AUR (there are somewhat different versions available) I see the program in the menu, but when I click on it noting seems to happen. Im in Manjaro 4.10.42-1.

Should it open it's own window, or can I see the effect in thunar somewhere?

**Comment by jstaf** [comment]
Try installing the `onedriver-git` package from the AUR. This is the pre-release package for the next version... notably it has an actual GUI that actually works and gives you feedback on what the state of things is (the old GUI would just launch a bash script that would try to mount OneDrive at ~/OneDrive). Feel free to open new issues if you have any problems with the new GUI - it's a rough "first pass" but is still a lot better than the old one.

**Comment by remcoNL** [comment]
Thank you! 

I installed the Git version and got this error during build
```
==> Starting build()...
make: Entering directory '/var/tmp/pamac-build-remco/onedrive-git/src/onedrive'
echo v1.1.4 >version
sed "s|@PREFIX@|/usr|g" onedrive.service.in > onedrive.service
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/qxor.d(67): Error: need `this` for `lengthInBytes` of type `immutable(ulong)`
make: *** [Makefile:32: onedrive] Error 1
make: Leaving directory '/var/tmp/pamac-build-remco/onedrive-git/src/onedrive'
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by abraunegg** [comment]
@remcoNL 
Unfortunately you have tried to install / compile the 'skilion' onedrive client .. which, is unsupported, unmaintained and has many defects which lead to data loss.

The correct package here should be: `onedriver-git` where as what you have tried to install is `onedrive-git`

FYI, for a supported & updated 'skilion' client, refer to:
* https://aur.archlinux.org/packages/onedrive-abraunegg/
* https://aur.archlinux.org/packages/onedrive-abraunegg-git/

**Comment by remcoNL** [comment]
Haha, my bad. I'll try again.

**Comment by remcoNL** [comment]
I've now installed ondriver-git 0.10.1.r3.g5c552cf-1

This gives no window, but is visible in the menu. 

I can't find the package onedriver-git (without the numbering), but i do see onedriver 0.10.1-4

**Comment by remcoNL** [comment]
Update: 
I tried to make a mount poit via the cli, it gave a fatal error. I just tried again via the menu and the window appeared! This is good. I then selected a mount point en nothing happened. Who knows what will happen tomorrow...

**Comment by jstaf** [comment]
What's the error? Try just making a directory and mounting things - for instance:

```
mkdir mountpoint
onedriver mountpoint
```

It almost sounds like onedriver is trying to open your default web browser (to authenticate with Microsoft), but you don't have a default web browser setup.

**Comment by remcoNL** [comment]
I got it working via the command line! This is fantastic, a really good tool!

I'm not sure why it didn't work yesterday, maybe there was a mistake in the path to the mount point (which is weird, since mkdir makes it, so it should exist). 

The GUI pops up but is empty. 

Any way, case closed, thanks very much. 

So what worked for me in Manjaro:

1. in Add/remove software find onedrive**r** and choose the git version to install
2. in the command line: `mkdir mountpoint`
3. in the command line: 'onedriver mountpoint'
4. in Session an Startup from the menu,  choose Application Autostart, choose the plus-sign, add as a Command: `onedriver mountpoint` (trigger: on login)

**Comment by jstaf** [comment]
The autostart behavior can also be handled by the systemd, check out https://github.com/jstaf/onedriver#multiple-drives-and-starting-onedrive-on-login-via-systemd if you want to set this up (the GUI will set this up for you - still not sure why it's not working for you).

If you're seeing errors with the GUI (or it doesn't start), let me know what happens when you run `onedriver-launcher` on the command line.
