### ISSUE TITLE
Have PPA support multiple Ubuntu versions

### ISSUE THREAD

**Issue by jstaf** [jstaf/onedriver#141]
Sort of a silly issue, but the Ubuntu Launchpad PPA interface is incredibly unclear on how to support different Ubuntu versions. We only have a build for 20.04 right now. Expand the onedriver deb releases to cover all of the currently supported Ubuntu versions >18.04.

**Comment by jstaf** [comment]
Looked into it a little bit last night and the process is pretty convoluted. Apparently you need to change the release in the changelog file to the targeted version, and ALSO add a version suffix (`~ubuntu18.04`) to all of the files included in the dput upload (which need to be signed as part of the .changes file, so we can't just rename them, we have to apply the name change *before* building the .changes file via `debuild`).

**Comment by danieltomasz** [comment]
Yes, I am on  Ubuntu 20.10 but I soon switch to 21.04, It will be nice to could use the app on my computer

**Comment by SwampRabbit** [comment]
@jstaf you could always go with something more vendor neutral like the openSUSE Build Service (OBS).  Don't let the name fool you, we (MX Linux) use it sometimes for stubborn packages or just to reduce internal packaging loads.  Its pretty darn easy to use and doesn't take much to get the hang of it.

> The openSUSE Build Service is the public instance of the Open Build Service (OBS) used for development of the openSUSE distribution and to offer packages from same source for Fedora, Debian, Ubuntu, SUSE Linux Enterprise and other distributions.

**Comment by jstaf** [comment]
That is an outstanding suggestion! Let me set that up. It would make me a very happy person if I never had to use Launchpad  again... 😅

**Comment by SwampRabbit** [comment]
@jstaf awesome, glad I could help, I do hope it works out better for ya.

There are a lot of pros to using OBS such as building for other architectures like ARM, being able to build dependencies with an application, etc, etc.  If more people used OBS over Launchpad, I know some projects would get more visibility and hopefully support than they do just sticking with Ubuntu.

**Comment by jstaf** [comment]
I switched the readme to provide instructions for installing packages directly from the new OBS repos tonight. Now Debian gets its own dedicated repos, and I don't have to jump through hoops to support multiple Ubuntu versions anymore. I'll still confess I prefer COPR for the RPM builds, but this is a major step up. 

Nice suggestion @SwampRabbit !
