### ISSUE TITLE
Add support for multiple drives

### ISSUE THREAD

**Issue by jstaf** [jstaf/onedriver#15]
* [x] Add support for multiple drives

**Comment by 0anton** [comment]
Support for multiple drives (e.g. personal and business) would be indeed a nice feature.
Also, operation in headless mode, e.g. providing credential without UI/browser interaction is very handy sometimes.
Besides that works perfectly! Thank you for the great tool!

**Comment by jstaf** [comment]
Aw thanks! Just as an FYI - headless mode is currently supported. You can build a headless version of onedriver with `CGO_ENABLED=0 go build ./cmd/onedriver`. You'll still have to go through the OAuth2 flow in a browser somewhere (it's the only way to authenticate to Microsoft's APIs), but it will have text instructions in the terminal that cover how to do so.

There's also a hack to get multiple drives setup (using the `--cache-dir` option - the only thing stopping you from running multiple onedriver instances to mount multiple drives is that they can't share the same cache directory), but I'm hoping to make this process easier in a future release.

I'm currently planning to tackle shared items / multiple drives once I write a GUI to help walk users through initial setup/checking to make sure everything's working.

**Comment by jstaf** [comment]
Added in #71. Going to create another issue re: making a GUI manager for multiple drives.
