### ISSUE TITLE
Provide user-friendly GUI / .desktop launcher

### ISSUE THREAD

**Issue by jstaf** [jstaf/onedriver#16]
* [ ] Create a nice GUI setup tool that lets you do the following without knowing anything about the command-line:
  * [ ] Choose a mount location
  * [ ] Start/stop onedriver and configure it to run on login
  * [ ] Get the onedriver logs out of systemd
* [ ] Create a .desktop launcher for the setup tool.
* [ ] Create some user-friendly docs pages (so you don't have to be a developer to get it working)

**Comment by jstaf** [comment]
Putting down my current thoughts down on this one:

We don't actually need a GUI, we just need a .desktop file to launch the app. I initially wondered about picking a mountpoint, but 99% of users will be fine with just a default mount directory (`~/OneDrive` ?) and having the .desktop file immediately open the OneDrive mount for them in their favorite file browser via `xdg-open`.

The app launched by the .desktop file can basically just be a bash script that does the following:

* check if a onedriver process is running
* if no process, mount one via systemd, and print a command on how to check the logs
* open the mounted folder via xdg-open

We can turn the launcher bash script into a fully-fledged go program with a file picker and buttons to enable the mount at boot and everything once we got support for multiple drives working (because then we'll probably need a GUI/other launch tool for most users to manage the multiple onedriver processes that are running).

**Comment by tseward** [comment]
I'd allow for the usage of multiple mount points -- i.e. I may want to mount personal OneDrive as well as OneDrive for Business.

**Comment by jstaf** [comment]
@tseward Better support for multiple mount points is happening, just not in this issue. Going to tackle having a setup utility for multiple accounts once I get a nice experience with a single account (baby steps, I guess).

Re: getting multiple accounts setup right now - you can actually already setup onedriver to use multiple accounts, just create a copy of the systemd unit file and change the `Exec` line to use a separate cache directory from the default with the `-c` option. (You can run as many onedriver instances / connect as many accounts as you like as long as they use different cache directories.)

**Comment by jstaf** [comment]
Closed in #63
