### ISSUE TITLE
Remote I/O error when opening OneNote documents

### ISSUE THREAD

**Issue by metronidazole** [jstaf/onedriver#162]
I have a number of OneNote workbooks stored on OneDrive. Whenever I try to open them with onedriver (e.g. less x), I receive a "Remote I/O error". Other files open fine.

Using onedriver 0.11.1

**Comment by jstaf** [comment]
For whatever reason, Microsoft does not allow accessing OneNote documents via OneDrive. There's another issue open to add an "ignore list" so you can exclude these files since they can't be opened (tracking things in #102).
