### ISSUE TITLE
Collaped Volume Name on Nautilus

### ISSUE THREAD

**Issue by jesuscastro-git** [jstaf/onedriver#180]
Hello, this is my first time using One Driver on gnome, and one thing I've noticed is that when the volume is mounted it displays the whole email in the sidebar of Nautilus (unlike other file explorers like Nemo or Dolphin that collapse the name), making it huge and bad looking. Is there any way to change the volume name, or just the possibility to collapse it?

Here's a screenshot of how it looks: https://i.imgur.com/evvpSFO.png

**Comment by jstaf** [comment]
Done in #394
