### ISSUE TITLE
Port to Debian 11 Bullseye

### ISSUE THREAD

**Issue by aiden21c** [jstaf/onedriver#195]
I know Debian 11 was released very recently, but unfortunately it seems that this client is unable to work with it at the moment. It currently hangs after inputting the 2FA code and then fails to mount. the logs unfortunately do not seem to report any errors, simply stating "No entries".

**Comment by jstaf** [comment]
I've added a Debian 11 build. I tried this out on the Debian 11 Live system and it appears to work. https://software.opensuse.org//download.html?project=home%3Ajstaf&package=onedriver

If you still have issues, try running the GUI via `onedriver-launcher` and let me know if there are any log messages there indicating issues + manually mount things and generate logs via `onedriver --log=trace /path/to/some/mountpoint`.

**Comment by aiden21c** [comment]
Awesome, Thank you for that. I will do some user tests this week and let you know how my experience is. Thanks again.

**Comment by aiden21c** [comment]
I have just been giving this a go on my Debian machine and unfortunately have had little luck. My problem originally was using the Debian 10 version of the application, when trying to mount my account the application would seemingly freeze and no mounting was possible. I tried the debian 11 version and this problem still persists. 

Running the launcher GUI via the terminal yielded the same results and no error logs were observed. I then tried `onedriver --log=trace /path/to/some/mountpoint` which at first seemed promising however after entering my credentials it failed to mount the Onedrive account, this time yielding some errors (I forgot to observe these tho). The mountpoint then dissapeared from my file manager (Dolphin), so I removed it in terminal and attempted to start again. Now I cant even get this command to bring up the sign in options for my onedrive account. This is the output of the command straight after an install of Onedriver:

`aiden@debian:~$ sudo onedriver --log=trace ~/Onedrive
INFO[2021-11-09T22:27:53]main.go:101 000001:main.main() onedriver v0.11.2 5b110be4                   
TRAC[2021-11-09T22:27:53]delta.go:18 000053:fs.(*Cache).DeltaLoop() Starting delta goroutine.                    
DEBU[2021-11-09T22:27:53]delta.go:21 000053:fs.(*Cache).DeltaLoop() Fetching deltas from server.                 
INFO[2021-11-09T22:27:54]delta.go:44 000053:fs.(*Cache).DeltaLoop() Fetched 0 deltas.                            
DEBU[2021-11-09T22:27:54]cache.go:525 000053:fs.(*Cache).SerializeAll() Serializing cache metadata to disk.          
^CINFO[2021-11-09T22:28:01]signal_handlers.go:16 000044:fs.UnmountHandler() Signal received, unmounting filesystem.       signal=INTERRUPT
aiden@debian:~$ sudo onedriver --log=trace ~/Onedrive
INFO[2021-11-09T22:29:02]main.go:101 000001:main.main() onedriver v0.11.2 5b110be4                   
TRAC[2021-11-09T22:29:08]delta.go:18 000007:fs.(*Cache).DeltaLoop() Starting delta goroutine.                    
DEBU[2021-11-09T22:29:08]delta.go:21 000007:fs.(*Cache).DeltaLoop() Fetching deltas from server.                 
INFO[2021-11-09T22:29:08]delta.go:44 000007:fs.(*Cache).DeltaLoop() Fetched 0 deltas.                            
DEBU[2021-11-09T22:29:08]cache.go:525 000007:fs.(*Cache).SerializeAll() Serializing cache metadata to disk.          
DEBU[2021-11-09T22:29:38]delta.go:21 000007:fs.(*Cache).DeltaLoop() Fetching deltas from server.                 
INFO[2021-11-09T22:29:38]delta.go:44 000007:fs.(*Cache).DeltaLoop() Fetched 0 deltas.                            
DEBU[2021-11-09T22:29:38]cache.go:525 000007:fs.(*Cache).SerializeAll() Serializing cache metadata to disk.          
DEBU[2021-11-09T22:30:08]delta.go:21 000007:fs.(*Cache).DeltaLoop() Fetching deltas from server.                 
INFO[2021-11-09T22:30:08]delta.go:44 000007:fs.(*Cache).DeltaLoop() Fetched 0 deltas.                            
DEBU[2021-11-09T22:30:08]cache.go:525 000007:fs.(*Cache).SerializeAll() Serializing cache metadata to disk.          
DEBU[2021-11-09T22:30:39]delta.go:21 000007:fs.(*Cache).DeltaLoop() Fetching deltas from server.                 
INFO[2021-11-09T22:30:39]delta.go:44 000007:fs.(*Cache).DeltaLoop() Fetched 0 deltas.                            
DEBU[2021-11-09T22:30:39]cache.go:525 000007:fs.(*Cache).SerializeAll() Serializing cache metadata to disk.          
DEBU[2021-11-09T22:31:09]delta.go:21 000007:fs.(*Cache).DeltaLoop() Fetching deltas from server.                 
INFO[2021-11-09T22:31:09]delta.go:44 000007:fs.(*Cache).DeltaLoop() Fetched 0 deltas.                            
DEBU[2021-11-09T22:31:09]cache.go:525 000007:fs.(*Cache).SerializeAll() Serializing cache metadata to disk.          
DEBU[2021-11-09T22:31:39]delta.go:21 000007:fs.(*Cache).DeltaLoop() Fetching deltas from server.                 
INFO[2021-11-09T22:31:40]delta.go:44 000007:fs.(*Cache).DeltaLoop() Fetched 0 deltas.                            
DEBU[2021-11-09T22:31:40]cache.go:525 000007:fs.(*Cache).SerializeAll() Serializing cache metadata to disk.          
DEBU[2021-11-09T22:32:10]delta.go:21 000007:fs.(*Cache).DeltaLoop() Fetching deltas from server.                 
INFO[2021-11-09T22:32:10]delta.go:44 000007:fs.(*Cache).DeltaLoop() Fetched 0 deltas.                            
DEBU[2021-11-09T22:32:10]cache.go:525 000007:fs.(*Cache).SerializeAll() Serializing cache metadata to disk.          
^CINFO[2021-11-09T22:32:14]signal_handlers.go:16 000032:fs.UnmountHandler() Signal received, unmounting filesystem.       signal=INTERRUPT`

**Comment by jstaf** [comment]
Ah, it looks like you are trying to mount the filesystem as the root user (ie. using `sudo`). FUSE filesystems don't allow access by `root` by default. The filesystem is running fine - the total absence of actual syscalls in the logs indicates that it's not receiving any requests (probably because the FUSE kernel module doesn't allow the root user to use FUSE filesystems by default).

onedriver has to run as an unprivileged/normal user (I should probably make it so running onedriver as root is a fatal error, with a special flag that allows root mounts). You can clean things up and try mounting it again via:

```bash
# wipe the onedriver cache as your user and as root to make extra sure you've got a clean slate
sudo onedriver -w
onedriver -w

# verify that you're not root and mount the filesystem again
whoami
onedriver ~/OneDrive

# in new window, list files in the filesystem
ls ~/OneDrive
```

**Comment by aiden21c** [comment]
Absolute legend @jstaf. Everything works great now and appears to be persistant between reboots. Thank you so much.
