### ISSUE TITLE
cached files shouldn't be in onedriver.db

### ISSUE THREAD

**Issue by sirber** [jstaf/onedriver#196]
Scenario: I have a 100GB music getting indexed by Clementine.

While indexing, onedriver takes up to 2GB ram and has avery high cpu usage, and the db size grow significantly.

I think it would be more efficient to store data in files outside the db, indexed by the database.

Thank you, and excellent project!

**Comment by sirber** [comment]
My DB is 100GB

![image](https://user-images.githubusercontent.com/3911428/140622168-9fa9b9d0-3e86-48fd-8b58-365509c974e3.png)

**Comment by sirber** [comment]
after a while, ram goes down, cpu stays high

**Comment by jstaf** [comment]
It doesn't directly solve the actual cause of the problem, but do you see an improvement if you build from `master`? There is a big optimization to the most problematic database transaction (writing the filesystem state to disk every 30s) that should improve things.

**Comment by sirber** [comment]
I'll try next weekend and keep you posted!

**Comment by sirber** [comment]
onedriver v0.12.0 1caf28a6

Scenario: having Clemtine indexing my 100GB music folder

CPU: bellow 25%
RAM: between 10% and 20%, increasing

**Comment by sirber** [comment]
I think this issue will resolve with the release of 0.12.0!

**Comment by sirber** [comment]
Looks good!

load average: 0.31, 0.19, 0.14
DB size: 26GB ... wierd

**Comment by sirber** [comment]
there we go!

![image](https://user-images.githubusercontent.com/3911428/140923718-f23c7402-e132-49c9-a62c-045e42e0cd4d.png)

the load on onedriver is fine!

**Comment by sirber** [comment]
onedriver ram is at 33%, will it go down eventually?

**Comment by jstaf** [comment]
There's an issue open to optimize memory usage more (#49), but the golang GC doesn't always release the memory immediately even if it's not used.

The easiest way to reduce memory usage is to just restart the filesystem (mount/unmount it in the GUI). It will settle at a much lower memory usage now that Clementine is done opening and indexing all of your music files.

**Comment by sirber** [comment]
It went down eventualy, 20% and 10%. It's good enough!
