### ISSUE TITLE
Copying large files fail

### ISSUE THREAD

**Issue by PixelDoted** [jstaf/onedriver#200]
If I try to copy a large file to my downloads folder from onedriver,
it fails to download the entire file it usually only downloads < 100MB

If I run "journalctl --user -u onedriver@.service" it doesn't show any errors
It's probably caused by linux copying the file before it's finished downloading
but i don't know

PopOS 21.04
Gnome 3.38
Kernel 5.13.0-7620-generic

**Comment by jstaf** [comment]
This should "just work" but I'd need to see the logfile - in this case `journalctl --user -u onedriver@ESCAPED_MOUNTPOINT.service`. Run `systemd-escape --template onedriver@.service --path MOUNTPOINT` to determine the value of `ESCAPED_MOUNTPOINT` to use. You will see output if the command succeeds (if you see `No entries` you've got the command isn't right).

**Comment by PixelDoted** [comment]
Here's the log (The file I'm trying to download is called "data.zip")
https://gist.github.com/PixelDoted/901fa93b4f2aa48625b9042bd0c2496e

**Comment by PixelDoted** [comment]
The 1.3 release of onedriver has fixed the issue (with the one file I tested),
Thanks :D
