### ISSUE TITLE
`GLIBC_2.32' not found

### ISSUE THREAD

**Issue by hmsjy2017** [jstaf/onedriver#202]
I built a deb package for Debian arm64. It can be installed without error. But when I run onedriver, it prompts `onedriver: /lib/aarch64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by onedriver)`. I tried to update libc6, but found that it is already the latest version (2.28).

**Comment by jstaf** [comment]
Hey this error comes from building the .deb for the wrong distribution version (each ships with a version of glibc specific to its version). You can change which distribution you build for by specifying which debian version to build for when you create a chroot: `sudo pbuilder create --distribution DISTRIBUTION_NAME`

If you're building for a raspberry pi, there is a Rasbian repo repos with aarch64 support - I recommend using those if you can: https://software.opensuse.org/download.html?project=home%3Ajstaf&package=onedriver
