### ISSUE TITLE
The name of the mounted partition is too long

### ISSUE THREAD

**Issue by xingji-27** [jstaf/onedriver#207]
Hope to support rename function after adding mount
![2021-11-21_11-52](https://user-images.githubusercontent.com/76865710/142749001-9ef523b5-c4b3-4a0c-8d46-ae7bc9b13668.png)

**Comment by jstaf** [comment]
You can rename the drive by following the instructions here: https://github.com/jstaf/onedriver/issues/146.

I am hoping to add a feature to do this in the UI in a future release.
