### ISSUE TITLE
Error Updating

### ISSUE THREAD

**Issue by aiden21c** [jstaf/onedriver#219]
I am running Onedriver on Debian 11 Bullseye and for some reason it appears that the new update refuses to install. Not sure if this might be my own system error or an issue with the newest update but the error is as follows:

`aiden@debian:~$ sudo apt update
[sudo] password for aiden: 
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease                                                                                           
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease                                                                            
Hit:4 http://download.virtualbox.org/virtualbox/debian bionic InRelease                                                                                 
Hit:5 http://deb.debian.org/debian buster-backports InRelease                                                                                           
Hit:6 https://packages.microsoft.com/repos/code stable InRelease                                                                                                          
Hit:7 https://dl.google.com/linux/chrome/deb stable InRelease                     
Hit:8 http://download.opensuse.org/repositories/home:/jstaf/Debian_11  InRelease  
Hit:9 https://fasttrack.debian.net/debian-fasttrack bullseye-fasttrack InRelease
Hit:10 https://fasttrack.debian.net/debian-fasttrack bullseye-backports-staging In
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
aiden@debian:~$ apt list --upgradable
Listing... Done
onedriver/unknown 0.12.0-1 amd64 [upgradable from: 0.12.0-1]
N: There is 1 additional version. Please use the '-a' switch to see it
aiden@debian:~$ apt list --upgradable -a
Listing... Done
onedriver/unknown 0.12.0-1 amd64 [upgradable from: 0.12.0-1]
onedriver/now 0.12.0-1 amd64 [installed,upgradable to: 0.12.0-1]

aiden@debian:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  onedriver
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/1,942 kB of archives.
After this operation, 4,096 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Reading changelogs... Done
Setting up install-info (6.7.0.dfsg.2-6) ...
/usr/sbin/update-info-dir: 1: /etc/environment: /snap/bin: Permission denied
dpkg: error processing package install-info (--configure):
 installed install-info package post-installation script subprocess returned error
Errors were encountered while processing:
 install-info
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by jstaf** [comment]
I suspect something is broken from a different package called `install-info`, as onedriver doesn't modify any of those files listed. (Debian/Ubuntu kind of have a bad package manager where package installation frequently breaks and then it continues breaking on subsequent installs.)

Try the solution listed here: https://askubuntu.com/questions/1069702/dpkg-error-processing-package-install-info
