### ISSUE TITLE
Pop_OS 21.10 Unable to locate package

### ISSUE THREAD

**Issue by Vviotti** [jstaf/onedriver#221]
After looking into the know issues, number #141 I saw the discussion on moving the distribution with the OBS, and I used that for Onedriver on the debian option, but I still got it the "Unable to locate package" when trying to install.

The repository is listed on the system and when running the and apt update the repository shows as a hit. So currently I have no idea where to go besides here. (Sorry if not clear I'm still learning linux as I transitioned from windows)

**Comment by jstaf** [comment]
I am guessing that you may have installed the repo for 20.10 or something like that by accident, so your system ignores the packages for the wrong OS version. What do you see when you run this? 

(Basically the instructions from OBS have you install a new repo and download the onedriver.deb package from that repo. These instructions will purge your existing repo if it exists and then re-add the repo for Ubuntu 21.10. Pop!_OS 21.10 is based off of Ubuntu 21.10.) 

```bash
# delete existing repo from system, if it exists
sudo rm -f /etc/apt/sources.list.d/home:jstaf.list

# install from ubuntu 21.10 repo
echo 'deb http://download.opensuse.org/repositories/home:/jstaf/xUbuntu_21.10/ /' | sudo tee /etc/apt/sources.list.d/home:jstaf.list
curl -fsSL https://download.opensuse.org/repositories/home:jstaf/xUbuntu_21.10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_jstaf.gpg > /dev/null
sudo apt update
sudo apt install onedriver
```

If that doesn't work, you can always install the package from the downloadable .deb file (just you won't automatically get updates): 

```bash
wget https://download.opensuse.org/repositories/home:/jstaf/xUbuntu_21.10/amd64/onedriver_0.12.0-1_amd64.deb
sudo apt install ./onedriver_0.12.0-1_amd64.deb
```

**Comment by Vviotti** [comment]
Worked like a charm. Reading over and over again I realized that I should had used the Ubuntu option on OBS, not the Debian. (Learning everyday...) I'll make a one time sponsor donation as appreciation for the support and also for the software that worked marvelously, unfortunately the economics in Brazil are not the best and I cant expend more. Thank you and keep up the good work. I'm no programmer but if I can assist in any other way let me know.

**Comment by jstaf** [comment]
No worries - glad things are working marvelously! You're actually my first sponsor since setting that up :tada:

Best way to help is just to report issues/come up with ideas for enhancements as you run into them. I've noticed that sometime my use cases for onedrive are different than other peoples' so I often don't hit all of the errors that other people may run into / my documentation can be left wanting (in the case of OBS I guess I should probably make it more clear what options people are supposed to pick).
