### ISSUE TITLE
Renaming Strategies

### ISSUE THREAD

**Issue by arunkumaraqm** [jstaf/onedriver#223]
I'm new to this software and need a folder synced to OneDrive. I have a folder on my computer say Foo which contains 500 files. I copy Foo onto the mounted folder and it uploads to OneDrive. If in the future, I use a bulk renamer to rename 50 files in the original Foo folder, how would I get that to reflect on OneDrive? Ideally, I'd not want to reupload the files. 

I could just use the bulk renamer in the mounted folder but I only plan on syncing up to Onedrive once a month while my file renaming occurs much more often.

**Comment by jstaf** [comment]
It all depends on how the bulk renamer works. If the renamer just renames or moves the file (the straightforwards way to do it), then onedriver will rename the file on OneDrive without reuploading the file.

On the other hand, if the renamer does something naughty and saves a copy of the file, then renames the copy to the new name, then deletes the old version of the file, this will result in the file being reuploaded. Software like LibreOffice/KeepassXC/Krita saves files this way and it always results in a reupload every time you save. 

I suspect that your bulk renaming software will "do the right thing" and simply rename the files (which means no reupload), but wanted to mention the other possibility. Hopefully this answers your question.

**Comment by arunkumaraqm** [comment]
> I use a bulk renamer to rename 50 files in the original Foo folder.

I was looking for something more in the lines of whether there was a software that would observe how I renamed them in the original Foo folder and reflect those renames in the "mounted" folder.

Anyway, I noticed that OneDrive share links don't work in my browser so I might have to switch to a different drive application.
