### ISSUE TITLE
Installation for Raspberry Pi running Ubuntu

### ISSUE THREAD

**Issue by bpavel88** [jstaf/onedriver#224]
I am running Ubuntu 21.10 on a Raspberry Pi. I attempted to follow the installation instruction on `Ubuntu/Pop!_OS/Debian`, but kept getting `Unable to locate package onedriver`. My assumption is this is due to the fact that in OBS, we have the packages for `AMD64` architecture, but Raspberry Pi is with `ARM64` (`aarch64`) architecture.

I came across the issue https://github.com/jstaf/onedriver/issues/87 , but `sudo add-apt-repository ppa:jstaf/onedriver` is not viable any longer. I am assuming that it has been removed since we have moved to start building Debian packages using OBS with https://github.com/jstaf/onedriver/pull/159 .

**Do you think it is possible to add the package for `ARM64` with Ubuntu?**

Also, I compiled and installed it from source and it started up.

**Comment by jstaf** [comment]
After some clicking around I was able to enable aarch64 builds for all .deb distros (not sure why I didn't figure this out earlier). :slightly_smiling_face: https://build.opensuse.org/repositories/home:jstaf

**Comment by bpavel88** [comment]
Thanks @jstaf . I will give it a swing and report back if something goes wrong.
