### ISSUE TITLE
Still in development? No fixes/responses from author

### ISSUE THREAD

**Issue by ga2k** [jstaf/onedriver#225]
Is this project still in development? I see the last couple of problems raised have not had answers for a couple of months. 

I'd like to try this out but if it's orphaned, it might be too big of a risk.

**Comment by jstaf** [comment]
Lol - yes, still in development. The update in November was huge.

As with a lot of Linux desktop software, onedriver currently has just one person developing it, and it's updated on an "as I feel like it" basis. I do this for fun, after all.
