### ISSUE TITLE
CLI cheatsheet somewhere? My server doesn't have a GUI

### ISSUE THREAD

**Issue by ga2k** [jstaf/onedriver#226]
Are there instructions somewhere for doing things like adding accounts from the CLI? I have a few Ubuntu and Arch servers that only run a terminal, with no GUI at all...

**Comment by ga2k** [comment]
Never mind. I should have tried onedriver --help before I wrote this :-(

**Comment by jstaf** [comment]
Also worth noting that there's a man page too! You can view it with `man onedriver`.
