### ISSUE TITLE
OpenSuse Repo for Raspian Buster / Bullseye 32bit

### ISSUE THREAD

**Issue by RichardBeisser** [jstaf/onedriver#236]
Hello

How is the correct entry for 32bit Version of Raspian in Repo-File for apt?
echo 'deb http://download.opensuse.org/repositories/home:/jstaf/Raspbian_11/ /' | sudo tee /etc/apt/sources.list.d/home:jstaf.list

With this entry, the package-Manager of Raspian only sugguest the arm64 deb-files which are for 64bit. I have tested it with synaptic.
Raspian needs the package located in armhf-Folder

64bit ist only neccessary for rPi4 with more than 4GB RAM. All other rPi run with 32bit Version.

Thanks.

**Comment by abraunegg** [comment]
@RichardBeisser 
> 64bit ist only neccessary for rPi4 with more than 4GB RAM. All other rPi run with 32bit Version.

I dont think this is entirely accurate. From this: https://forums.raspberrypi.com/viewtopic.php?t=232338 

> The Raspberry Pi 2B v1.2 / 3B / 3B+ / 3A+ SBCs, all use the BCM2837 Cortex-A53 (ARMv8) 64-bit SoC.

Most people still install the 32-Bit versions of *whatever* because that's what *most* instructions out there on the Internet direct you to do .. but you most certainly can run 64-Bit versions of Debian & Raspbian or whatever (Ubuntu etc) on those devices. If you use the `kernel8.img` as your kernel - you are running a 64-Bit Kernel.

How can you tell what architecture you are running? You can use `uname -a` or `arch` to find out:

**Raspbian on Raspberry Pi 2 Model B** - Specifically loading `kernel7.img`
```
Linux raspberrypi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux
```
Note the `armv7l` - this is running as 32-Bit with 32-Bit Kernel

**Raspbian on Raspberry Pi 2 Model B** - Specifically loading `kernel8.img`, same hardware as above
```
Linux raspberrypi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 GMT 2020 aarch64
```
Note the `aarch64` - this is running as 64-Bit with 64-Bit Kernel

IMHO you should be using a 64-Bit OS whenever possible - and avoid using 32-Bit OS installations for a variety of reasons - performance, stability being the main reasons.

**Comment by RichardBeisser** [comment]
> > 64bit ist only neccessary
> Most people still install the 32-Bit versions of _whatever_ because that's what _most_ instructions out there on the Internet direct you to do .. but you most certainly can run 64-Bit versions of Debian & Raspbian or whatever (Ubuntu etc) on those devices.

 yes, you are absolutely right. That's why I wrote "neccessary". You must use 64bit to address the whole 8GB RAM of rPi4. all other rPis have less RAM, so you can use 32bit.
Of course, you can use the 64bit Raspian on the devices with 4GB RAM or less. These devices have also a 64bit architecture.
I installed Raspian for all my rPis in 2019. In 2019, 64bit was in beta state. So 64bit Raspian is very new.


> How can you tell what architecture you are running? You can use `uname -a` or `arch` to find out:

Linux homePi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

> IMHO you should be using a 64-Bit OS whenever possible - and avoid using 32-Bit OS installations for a variety of reasons - performance, stability being the main reasons.

As I wrote, i installed Raspian on different devices. I never kept oneselv busy with how to migrate from 32bit to 64bit. I suppose (not knowing) that you have to install Raspian from beginning, that there is no way to migrate a running system.

**Comment by jstaf** [comment]
Just asking for some quick clarification:

* Are you asking for a new architecture here for builds (armv6l/armel)?
* Or is the problem that when you add the repository, it doesn't find the armv7l/armhf binaries? http://download.opensuse.org/repositories/home:/jstaf/Raspbian_11/armhf/

I can enable the build for armv6l (currently have builds enabled for armv7l and aarch64), but it sounds like you have an armv7l system. I did some googling and https://wiki.debian.org/RaspberryPi seems to suggest that armel/armv6l is only required for the Rasberry Pi 1 (which is almost 10 years old now).

**Comment by RichardBeisser** [comment]
> Just asking for some quick clarification:
> 
>     * Or is the problem that when you add the repository, it doesn't find the armv7l/armhf binaries? http://download.opensuse.org/repositories/home:/jstaf/Raspbian_11/armhf/

it's only the question of how to use repo for armhf.
the armhf-deb-file itself is working

**Comment by jstaf** [comment]
Try this out - edit `/etc/apt/sources.list.d/home:jstaf.list` and change the file contents to (adding the `[arch=armhf]` bit, which I *think* will force it to use the armhf packages):

```
deb [arch=armhf] http://download.opensuse.org/repositories/home:/jstaf/Raspbian_11/ /
```

(Also, just out of curiosity, what does this show: `dpkg --print-architecture`?)

**Comment by RichardBeisser** [comment]
> Try this out - edit `/etc/apt/sources.list.d/home:jstaf.list` and change the file contents to (adding the `[arch=armhf]` bit, which I _think_ will force it to use the armhf packages):
> 
> ```
> deb [arch=armhf] http://download.opensuse.org/repositories/home:/jstaf/Raspbian_11/ /

![Unbenannt](https://user-images.githubusercontent.com/47367173/152658902-00378538-c04b-4064-8d84-d2ff553afcc3.png)

> (Also, just out of curiosity, what does this show: `dpkg --print-architecture`?)

--> armhf

**Comment by jstaf** [comment]
I'm not sure what synaptic is doing here, this may be a problem with synaptic... does `sudo apt update` and `sudo apt install onedriver` give you the right package?

**Comment by RichardBeisser** [comment]
`sudo apt install onedriver` give you the right package?
yes, with this, you can install onedriver.
after that, onedriver (without ending arm64) is shown in synaptic

**Comment by jstaf** [comment]
Ok, I think this is a bug with Synaptic showing the wrong package in its UI. Going to close this as I don't think this is something wrong with onedriver or onedriver's packaging. (The actual `apt` package manager is doing the correct thing here.)
