### ISSUE TITLE
I can't run a program ¨C¨ code, directly from one drive using visual studio code

### ISSUE THREAD

**Issue by Alan007BR** [jstaf/onedriver#237]
¨final binding failed: Connection termination caused by software¨ this is what returns in my terminal, the onedriver client seems to be blocking the vscode entry in the folder

![image](https://user-images.githubusercontent.com/24919368/152681992-7fd8ccfb-aee6-415d-9db3-d6f461a84022.png)
It's in Portuguese in the photo

**Comment by jstaf** [comment]
I think this was fixed in https://github.com/jstaf/onedriver/issues/175. Make sure you're using the latest version (0.12.0).
