### ISSUE TITLE
"Need admin approval"

### ISSUE THREAD

**Issue by QazCetelic** [jstaf/onedriver#238]
I'm using a Microsoft education account and receive the following after completing the login procedure.
![image](https://user-images.githubusercontent.com/51381523/152992018-0bac8a9f-d418-4528-9c68-1522df567ec5.png)

Is this intended to be limited to personal accounts, or is this a bug?

**Comment by jstaf** [comment]
It's not intended to be limited to personal accounts and unfortunately this is not a bug. The administrator of your organization has put a restriction on third-party apps from connecting to the OneDrive API under your organization. You'll need to ask your administrator of your org to allow the app.

**Comment by QazCetelic** [comment]
Okay, in that case this issue can be closed.

**Comment by SLGASuwa** [comment]
Hi there, I have the same problem. @jstaf is there an app ID for this? I don't see it in the app gallery in Azure for be able to authorize. Thank you!
