### ISSUE TITLE
Local copy instead of tranferred to OneDrive

### ISSUE THREAD

**Issue by KC-T** [jstaf/onedriver#242]
I used Rclone on Ubuntu to copy files more than 1T to a directory  "abc" mounted by onedriver to OneDrive.  Initially, the copying seems OK but after a few hours, the harddisk containing "abc" has become full with files stored under "abc" instead of being transferred to OneDriver, though the copying is still running. Stopping the copying and deleting "abc" can release the disk space.

Is it a problem with onedriver or Rclone? How can the local copy be skipped. I am not talking about the .cache files.

Thanks!

**Comment by jstaf** [comment]
I suggest using rclone directly if you just want to copy directly to OneDrive (the onedriver mountpoint isn't necessary, you can perform a one-way sync with rclone).

**Comment by KC-T** [comment]
Thank you!
