### ISSUE TITLE
Shared folder is not accessible.

### ISSUE THREAD

**Issue by freeman1289** [jstaf/onedriver#252]
Users who shares a folder with me on OneDrive does not work. Instead of displaying the shared folder, a text file is created which does nothing. However, directly uploading documents to OneDrive work perfectly.

**Comment by cfgobel** [comment]
the same happens to me

**Comment by jstaf** [comment]
Shared folders aren't supported yet.

**Comment by jstaf** [comment]
This is getting worked on in #70. (Closing this so there's only one issue for shared items.)
