### ISSUE TITLE
Pop_OS! 21.04 suport ?

### ISSUE THREAD

**Issue by deverebor** [jstaf/onedriver#253]
Hi! I would like to know if the app is expected to be updated to version 22.04 LTS, the only reason you haven't changed your version is your app!
Congratulations on the project.

**Comment by jstaf** [comment]
Of course! I will update it as soon as there's support for Ubuntu 22.04 on the OpenSUSE Build Service. In the meantime, don't let that stop you from upgrading - you can actually build the .deb release for your current OS version by following the instructions here: https://github.com/jstaf/onedriver/wiki/Releasing-new-versions#pop_osdebianubuntu-and-variants

Copy/pasted:

```
# install build dependencies
sudo apt update
sudo apt install golang gcc libwebkit2gtk-4.0-dev libjson-glib-dev pkg-config git \
    rsync devscripts debhelper build-essential pbuilder
sudo pbuilder create --distribution jammy  # i think "jammy" is the right release name for 22.04

make deb
```

**Comment by deverebor** [comment]
Dude you are amazing! Thanks for responding so quickly and for helping, your software is one of the focal points of my workflow. Success and all the best.

Salute my brother!!

**Comment by jstaf** [comment]
Ok, I checked back again today while procrastinating on some stuff around the house, and there's an OpenSUSE 22.04 chroot now. So now there are official 22.04 packages :grin:
