### ISSUE TITLE
Cannot setup COPR for this project on RHEL9

### ISSUE THREAD

**Issue by theunclemez** [jstaf/onedriver#264]
I simply cannot setup the COPR for adding this app on my RHEL 9 fresh install, it works on OpenSuse with an alert of repond.xml not being signed but on RHEL it displays the below
![123](https://user-images.githubusercontent.com/50036470/174607927-ee4935f3-d9f9-47aa-85cc-95e108f25ef5.jpg)

Please do provide a good fix, there is no other project offering the same as what you offer

**Comment by jstaf** [comment]
There is now a EPEL 9 and CentOS Stream 9 build: https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/build/4557247/. `sudo dnf install onedriver` should work now :slightly_smiling_face:
