### ISSUE TITLE
command-line workflow

### ISSUE THREAD

**Issue by rrodrigueznt** [jstaf/onedriver#265]
Hi! Please, where could I find documentation about the command-line workflow [README.md](https://github.com/jstaf/onedriver#readme) talks about?

Thanks!

**Comment by jstaf** [comment]
It's in the README here: https://github.com/jstaf/onedriver#multiple-drives-and-starting-onedrive-on-login-via-systemd

**Comment by jstaf** [comment]
Try using the `--no-browser` option. See https://github.com/jstaf/onedriver/issues/259#issuecomment-1152993178
