### ISSUE TITLE
onedriver from home:jstaf project does not work on mx linux

### ISSUE THREAD

**Issue by khewweifeng** [jstaf/onedriver#266]
Debian 11 stable repo and .deb package not working

for .deb package it does not prompt any message 

for repo, here are the error message as below 

kurinorton@poro:~
$ echo 'deb http://download.opensuse.org/repositories/home:/jstaf/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/home:jstaf.list
[sudo] password for kurinorton: 
deb http://download.opensuse.org/repositories/home:/jstaf/Debian_11/ /
kurinorton@poro:~
$ curl -fsSL https://download.opensuse.org/repositories/home:jstaf/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_jstaf.gpg > /dev/null
kurinorton@poro:~
$ sudo apt update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease         
Hit:3 http://deb.debian.org/debian bullseye InRelease                 
Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease         
Hit:5 https://mirror.kku.ac.th/mx-packages/mx/repo bullseye InRelease
Get:6 http://download.opensuse.org/repositories/home:/jstaf/Debian_11  InRelease [1,507 B]
Get:7 http://download.opensuse.org/repositories/home:/jstaf/Debian_11  Packages [1,323 B]
Fetched 2,830 B in 1s (2,117 B/s)     
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
kurinorton@poro:~
$ sudo apt install onedriver
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libbotan-2-17 libqt5sensors5 libqt5webkit5 libtspi1
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  onedriver
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,945 kB of archives.
After this operation, 6,225 kB of additional disk space will be used.
Get:1 http://download.opensuse.org/repositories/home:/jstaf/Debian_11  onedriver 0.12.0-1 [1,945 kB]
Err:1 http://download.opensuse.org/repositories/home:/jstaf/Debian_11  onedriver 0.12.0-1
  File has unexpected size (1944244 != 1944756). Mirror sync in progress? [IP: 82.209.230.71 80]
  Hashes of expected file:
   - SHA256:16087f3aadc270295d755dffe7c8a1a3f3e90ad6f60fbe2d32bd6da962d7fca3
   - SHA1:4175a04195b1d0338d862c6a4a2f26b2016ce45b [weak]
   - MD5Sum:fd4fa8db21bd1bfabc77d947e2b3b875 [weak]
   - Filesize:1944756 [weak]
E: Failed to fetch http://ftp.byfly.by/pub/opensuse/repositories/home:/jstaf/Debian_11/amd64/onedriver_0.12.0-1_amd64.deb  File has unexpected size (1944244 != 1944756). Mirror sync in progress? [IP: 82.209.230.71 80]
   Hashes of expected file:
    - SHA256:16087f3aadc270295d755dffe7c8a1a3f3e90ad6f60fbe2d32bd6da962d7fca3
    - SHA1:4175a04195b1d0338d862c6a4a2f26b2016ce45b [weak]
    - MD5Sum:fd4fa8db21bd1bfabc77d947e2b3b875 [weak]
    - Filesize:1944756 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
kurinorton@poro:~
$

**Comment by khewweifeng** [comment]
![image](https://user-images.githubusercontent.com/54496743/178143459-3625367f-58c3-4757-aae4-8f3ea5c9baa5.png)

pc specs

**Comment by khewweifeng** [comment]
link = https://software.opensuse.org/download.html?project=home%3Ajstaf&package=onedriver

**Comment by jstaf** [comment]
Look like a bad mirror, try doing `sudo apt update` again and then `sudo apt install onedriver`. (It should try to download from a different .deb mirror)

**Comment by khewweifeng** [comment]
> Look like a bad mirror, try doing `sudo apt update` again and then `sudo apt install onedriver`. (It should try to download from a different .deb mirror)

install from repo was working but .deb package no idea why it does not run on mx linux

**Comment by khewweifeng** [comment]
installed but when comes to auth, onedriver will auto close

**Comment by jstaf** [comment]
What is the error from the logs? You can try using `onedriver /some/empty/folder` to test things out.

**Comment by jstaf** [comment]
Closing, as its a really old version and I didn't hear back in over a year.
