### ISSUE TITLE
Installing Issues

### ISSUE THREAD

**Issue by allen546** [jstaf/onedriver#268]
I'm trying to install onedriver, on a raspberrypi running raspbian bullseye, but:
(1) the builds on opensuse don't work; several dependencies uninstallable including libwebkit2gtk and fuse ( bypassed by using libfuse3 instead). 
(2) when running apt update after adding the repositories, it gets stuck on Get 4. If it's not a onedriver issue, ignore it. 
(3) I can't seem to install libwebkit2gtk, but it's bypassed by installing the 4.0-37 version. It's probably easier installed by changing the dependency to libwebkit2gtk only, not that version only.
(4) I'm using it from china, on linux, so I cannot use a vpn, and the makefile says it needs to get something from https://proxy.golang.org (Get #2). It always gets stck. Is there a way to bypass this?

**Comment by jstaf** [comment]
1. Hmm, it should have all the dependencies installable (or the build of the package shouldn't have worked in the first place, as those dependencies are required for OBS to build the package).

2. I suspect this is the same problem as 2, some of the OBS mirrors might be blocked in China (does `sudo apt clean all && sudo apt update && sudo apt install onedriver` fix it again? that might give you a different mirror)

3. Hmmm, what do you see when trying to install libwebkit2gtk-4.0-37 via apt? That should be the version that the debian package tries to install: https://github.com/jstaf/onedriver/blob/master/debian/control#L13

4. According to https://arslan.io/2019/08/02/why-you-should-use-a-go-module-proxy/ apparently the default Go module proxy is blocked in China- you can get around it by setting either `export GOPROXY=direct` (no proxy) or `export GOPROXY=https://goproxy.cn` (a proxy that isn't blocked).

**Comment by jstaf** [comment]
No response in awhile, assuming that fixed things
