### ISSUE TITLE
Help install onedrive on kubuntu 22.10

### ISSUE THREAD

**Issue by BimerBoy** [jstaf/onedriver#269]
Hi, I wanted to install it on kubuntu 22.10 but it gives an error, tell me how to fix it, or install it step by step, please. I'm new to linux.

this command does not work

echo 'deb http://download.opensuse.org/repositories/home:/jstaf/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:jstaf.list
curl -fsSL https://download.opensuse.org/repositories/home:jstaf/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_jstaf.gpg > /dev/null
sudo apt update
sudo apt install onedriver

**Comment by jstaf** [comment]
Please post the error message. I can't help you without knowing the actual error you got.

**Comment by BimerBoy** [comment]
> Пожалуйста, опубликуйте сообщение об ошибке. Я не могу помочь вам, не зная фактической ошибки, которую вы получили.

it informs me that the package is not found

**Comment by jstaf** [comment]
Oh, you've installed the repo for 22.04 and you are on 22.10. Those are different OS versions with different available packages. Ubuntu 22.10 isn't released yet (I don't even have a build for 22.10 right now), I'm assuming you are running 21.10?

If you're running Ubuntu 21.10: delete the existing repository on your system: `sudo rm /etc/apt/sources.list.d/home:jstaf.list` and then make sure you install the repository for Ubuntu 21.10 (assuming thats the version you're on).

If you are indeed running a beta version of Ubuntu 22.10, you can still compile onedriver from source (see the readme on the front page of this repo for instructions on how to do this).

**Comment by BimerBoy** [comment]
> О, вы установили репозиторий для 22.04 и находитесь на 22.10. Это разные версии ОС с разными доступными пакетами. Ubuntu 22.10 еще не выпущена (у меня даже нет сборки для 22.10 прямо сейчас), я предполагаю, что вы используете 21.10?
> 
> Если вы используете Ubuntu 21.10: удалите существующий репозиторий в вашей системе, а затем убедитесь, что вы установили репозиторий для Ubuntu 21.10 (предполагая, что это версия, на которой вы находитесь).`sudo rm /etc/apt/sources.list.d/home:jstaf.list`
> 
> Если вы действительно используете бета-версию Ubuntu 22.10, вы все равно можете скомпилировать onedriver из исходного кода (см. readme на главной странице этого репозитория для инструкций о том, как это сделать).

That's right, I have version 22.10 beta. OK, I'll look at the instructions now, but I think I won't understand anything there anyway =)

**Comment by jstaf** [comment]
Hey, hopefully you were able to compile from source (you can create a .deb via these instructions https://github.com/jstaf/onedriver#installation-from-source). Going to close this one out, let me know if you are still having issues!
