### ISSUE TITLE
[Question] How to install onedriver on Ubuntu 18.04?

### ISSUE THREAD

**Issue by Rullec** [jstaf/onedriver#279]
Thanks for your excellent project!

In the README.md, It's recommend to install onedriver by OBS. But I found there are only packages prepared for >= Ubuntu 20.04.

At this moment, How can I install it for Ubuntu 18.04 readily?

**Comment by jstaf** [comment]
That is a good question - I recall there is some issue with packaging for Ubuntu 18.04 (it was probably the version of Golang available). Try this out:

* Install a version of golang from https://go.dev/dl/, and `sudo apt install golang gcc libwebkit2gtk-4.0-dev libjson-glib-dev pkg-config git`. (The version of golang from Ubuntu 18.04 I think is too old.)
* Try `make` and `sudo make install`

Let me know if that doesn't work.

**Comment by jstaf** [comment]
(Going to assume that fixed things)
