### ISSUE TITLE
"Gdk-ERROR"?

### ISSUE THREAD

**Issue by NickelWW** [jstaf/onedriver#282]
I'm using the latest version of PopOS (22.04, I think?) and I get this error message.
I installed onedriver via opensuse.org.
Thanks for any help :)

===================================================================

nickelw@pop-os:~$ onedriver /home/nickelw/onedrive
16:30:48 INF onedriver v0.12.0 73d93207
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal

(WebKitWebProcess:45286): GLib-CRITICAL **: 16:30:48.198: Failed to set scheduler settings: Operation not permitted

(WebKitWebProcess:45286): Gdk-ERROR **: 16:30:48.278: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 208 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
16:31:59 FTL No validation code returned, or code was invalid. Please restart the application and try again.
nickelw@pop-os:~$

===================================================================

**Comment by jstaf** [comment]
That is an incredibly cryptic error. Unfortunately the error itself is in WebKitGTK (the library that provides an integrated browser that onedriver uses for authentication). You can try authenticating with `--no-browser` as a workaround (see this post on how to do so https://github.com/jstaf/onedriver/issues/259#issuecomment-1152993178).

I'd probably need to investigate with a Pop!_OS 22.04 install of my own (or someone would need to confirm this is happening with a vanilla Pop!_OS 22.04 with nothing else installed on it). Will leave this open to look into later.

**Comment by NickelWW** [comment]
Sorry I should've updated earlier, It was simply user error. I had mounted a drive improperly, and nothing really functioned properly on it. I looked up a tutorial on how to mount additional drives, and that fixed it.
