### ISSUE TITLE
Move file contents to filesystem instead of db

### ISSUE THREAD

**Issue by jstaf** [jstaf/onedriver#291]
We should store file contents on the actual filesystem instead of in boltdb. This would allow file uploads and downloads to no longer constrained by memory.

**Comment by sirber** [comment]
Great idea. The DB could be used for metadata, and not content. I just got a crash trying to upload a 1.1GB zip file, on a 16GB ram + 32GB swap machine.

**Comment by jstaf** [comment]
Closed in #331
