### ISSUE TITLE
How to install it on server and not  install GUI debdependence.

### ISSUE THREAD

**Issue by lyj0309** [jstaf/onedriver#294]
I have a debian server without GUI ,when i try to install it , there will install may debdependence like GUI, it's cost many storage, is there anyway not install it and run run this? 

![image](https://user-images.githubusercontent.com/50474995/197383615-2d64fafa-e664-4aad-8533-6ea07abda7f8.png)

**Comment by jstaf** [comment]
Compile it yourself with `CGO_ENABLED=0` if you want a build without GUI dependencies.
