### ISSUE TITLE
cannot mount onedrive on fedora 36

### ISSUE THREAD

**Issue by a-zmz** [jstaf/onedriver#296]
Hi,

I can no longer mount my onedrive on Fedora 36. Tried reinstall several time, no luck so far, and the problem stays: after clicking "add a new onedrive account", i get to select the folder, but it does not prompt me for logging in. In the end, the local address for mounting appears in onedriver GUI.

Could anyone please help? Thanks!

**Comment by a-zmz** [comment]
> Hi,
> 
> I can no longer mount my onedrive on Fedora 36. Tried reinstall several time, no luck so far, and the problem stays: after clicking "add a new onedrive account", i get to select the folder, but it does not prompt me for logging in. In the end, the local address for mounting appears in onedriver GUI.
> 
> Could anyone please help? Thanks!

btw, the version i have is onedriver-0.12.0-1.fc36.x86_64, installed via`sudo dnf install`.

**Comment by jstaf** [comment]
What happens when you run `onedriver-launcher` from the command line (this just starts the GUI from a terminal, so you'll see any logs it produces) and then try to mount a drive?

**Comment by a-zmz** [comment]
hi, i get an error message: `error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

**Comment by a-zmz** [comment]
i have updated to 0.13.0-1, and the problem remains...

**Comment by a-zmz** [comment]
problem solved after installing libatomic1 and libatomic dependency, thanks for the great software!
