### ISSUE TITLE
Is it needed a configuration file?

### ISSUE THREAD

**Issue by lobaluna** [jstaf/onedriver#306]
After I launched onedriver `/mnt/point`, I get this warning:

```
14:06:19 WRN Configuration file not found, using defaults. error="open /home/lobaluna/.config/onedriver/config.yml: no such file or directory" path=/home/lobaluna/.config/onedriver/config.yml
14:06:19 FTL Mountpoint must be empty. mountpoint=/mnt/homedata/onedrive
```

**Do I have to have a `conf.yml`?** I cannot find what to put in there. I guess, a moint point, but what is the key-value pair?

Besides, the warning says that the moint point must be empty, but it already has the files from a previous mounting operation. I'm not complaining in any way, just making it noticeble that I still can have a functional mount point.

**Comment by jstaf** [comment]
Nope, it's a totally optional thing if you want to add a configuration file. Most users don't need one. And yeah if a previous mount command is still running, the files will be present. Only one copy of onedriver can be running for a given mountpoint.
