### ISSUE TITLE
Dolphin freezes when Onedriver is running

### ISSUE THREAD

**Issue by cfleidl-gachea** [jstaf/onedriver#307]
When Onedrive is running Dolphin becomes slow and even freezes. I also see that it has a memory leak, it consumes huge amounts of RAM. (Attached Screenshot)

![Screenshot_20221216_164648](https://user-images.githubusercontent.com/92320450/208178172-45ef8e26-bb69-4cc6-8915-b2fb38baf7d4.png)

MY SYSTEM SPECS:
OS: EndeavourOS Linux x86_64 
Host: ZenBook Pro 15 UX550GEX_UX580GE 1.0 
Kernel: 6.0.12-zen1-1-zen 
Uptime: 18 mins 
Packages: 1904 (pacman), 8 (flatpak) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: Plasma 5.26.4 
WM: KWin 
Theme: Breeze Dark [Plasma], Layan-Light [GTK2/3] 
Icons: [Plasma], Tela [GTK2/3] 
Terminal: konsole 
CPU: Intel i7-8750H (12) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
Memory: 2799MiB / 15844MiB (Onedriver disabled)

**Comment by jstaf** [comment]
It's not a memory leak, the memory is currently in use. In a future version of the application, this will be solved by https://github.com/jstaf/onedriver/issues/291 

It's not actually Dolphin (or Onedriver) being slow, it's the fact that Dolphin is trying to create a thumbnail image of every single file in each directory. So it forces you to wait while it downloads each file in a directory the first time you open it while it creates thumbnail images for your filebrowser. Yes, this is super annoying, but it is the default behavior of most file browsers like Dolphin and Nautilus and I haven't found a good way to disable it.
