### ISSUE TITLE
OneDriver won't run on Zorin OS

### ISSUE THREAD

**Issue by muirj101** [jstaf/onedriver#317]
When I try to install OneDriver after adding the repos or downloading the package, OneDriver won't open. After running it in the terminal, I get the message "/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by onedriver)" and "/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by onedriver)".

Any ideas for a fix?

**Comment by jstaf** [comment]
You've installed the wrong package for your OS. It looks like Zorin OS is based on Ubuntu 20.04, so you should uninstall onedriver and then install the version for Ubuntu 20.04.
