### ISSUE TITLE
[Question] When or how does onedriver decide when to sync?

### ISSUE THREAD

**Issue by patrickfeeney03** [jstaf/onedriver#328]
When using Obsidian Md to modify files from my vault that are located inside the One Drive folder, the changes wont get uploaded until I close and re open Obsidian. I'm not sure what triggers the uploading of the modified files. When I modify a file and inside Obsidian, and it doesn't get uploaded, I can see these with its content by using the file explorer.
What is the event that triggers the file uploading? Or how can I go about controlling it? I'm sorry that I have to ask this here but I din't find anything about this on the main GitHub page of this software.

**Comment by patrickfeeney03** [comment]
Even when the files are modifies they don't always sync to online OneDrive. I need to close Obsidian and re open it for the file .md file to sync. If I only close Obsidian it won't sync, I need to close it and open it.

**Comment by jstaf** [comment]
That's pretty weird behavior. Usually files are synced on save and/or closing a file (specifically, uploads are triggered by the fsync or flush syscalls). If there are a ton of files to be uploaded at the same time, they have to wait in a queue (only 5 files get uploaded at a time). 

You can see when Onedriver is "asked" to do things by checking the logs (see the readme on the front page of this repo for more info). This will show when Obsidian is actually doing things that triggers an upload.

**Comment by patrickfeeney03** [comment]
Thanks for you response.

**Comment by heinsenberg82** [comment]
I'm observing the same exact behaviour in a brand new vault with only one file.
