### ISSUE TITLE
Depreciation of sha1hash for OneDrive Personal in July 2023

### ISSUE THREAD

**Issue by abraunegg** [jstaf/onedriver#332]
@jstaf 
Unsure if you have seen this: https://devblogs.microsoft.com/microsoft365dev/deprecation-of-sha1hash-on-onedrive-personal/

If you are relying on sha1 anywhere for the file hash, this will have to be updated to 'quickXorHash' or 'sha256Hash'

**Comment by jstaf** [comment]
Oh, that's fun :sweat_smile:. Well at least one upside of this is now I don't have to check both hash types depending on what type of drive it is.
