### ISSUE TITLE
I can't compile it

### ISSUE THREAD

**Issue by abtye** [jstaf/onedriver#336]
My device only has `7GB` of storage space, and OneDriver is of great significance to it. 
Its CPU is based on the `armhf` architecture, and it can also run `armv7l` or `amrv6l` code. 
But it can't run the code for `arm64`
I cannot compile it on my own, the following is the error message:
```
CGO_CFLAGS=-Wno-deprecated-declarations go build -v \
	-ldflags="-X github.com/jstaf/onedriver/cmd/common.commit=e2ef1e48e938c3c383e159701a6f8289723bb73a" \
	./cmd/onedriver
github.com/jstaf/onedriver/fs
# github.com/jstaf/onedriver/fs
fs/content_cache.go:32:16: undefined: os.ReadFile
fs/content_cache.go:38:9: undefined: os.WriteFile
make: *** [Makefile:21：onedriver] Error 2
```
To be honest, I don't understand GoLang, so I can only rely on you, man, help me!

**Comment by jstaf** [comment]
What does `go --version` show? I'm guessing I was somewhat naughty recently and used newer Golang features (1.16+), and your installed version of Golang is too old.

Never fear however - you have two options:

* Checkout the latest release 0.13.0 (this is the old version that will work with your golang version): `git checkout v0.13.0-2`
* Or if you really want to try the new experimental changes I made in the last week, uninstall golang, and install a newer version direct from the official site https://go.dev/dl/ (it looks like they have an armv6l version for you), then try compiling again.

**Comment by abtye** [comment]
I have updated the version of GoLang, and its current version is` go version go1.20.5 Linux/arm `.
There are no errors reported now, but I compiled for an hour and still haven't completed the compilation
```
CGO_ CFLAGS=- No reported declarations go build - v\
-Ldflags="- X github. com/jstaf/onedriver/cmd/common. common=e2ef1e48e938c3c383e159701a6f8289723bb73a"\
./cmd/onedriver
Github. com/gotk3/gotk3/gtk
```
It has been parked here for **an hour**.
- Perhaps my device configuration is too low to meet the minimum requirements for compilation?
My device's CPU only has four `1.536GHz` cores and `1GB` of memory.
- Or is it a network issue? In China, visiting GitHub is always not smooth.

**Comment by jstaf** [comment]
lol, gotk3 (the Go bindings for the GTK GUI framework) just takes forever to compile. Just let it do its thing and it will eventually finish. It takes me about 15 minutes to compile on a semi-fast laptop. But you're not alone, just need to wait!

* https://github.com/gotk3/gotk3/issues/837
* https://github.com/gotk3/gotk3/issues/843

If your device doesn't need a GUI, you can get a super fast/normal compile time by setting `export CGO_ENABLED=0` (this will disable the GUI, but if you're doing things on a raspberry pi or other server-like environment that doesn't have a UI, this is probably fine).
