### ISSUE TITLE
Question about Approval Required

### ISSUE THREAD

**Issue by grassdne** [jstaf/onedriver#348]
Thanks for creating such an awesome Linux OneDrive client! :heart: 

Authorizing jstaf/onedriver for my university account requests approval by administration, where as abraunegg/onedrive is allowed.
Has my organization already specifically whitelisted abraunegg/onedrive?
Or does jstaf/onedriver have different permissions which aren't allowed by default?

**Comment by jstaf** [comment]
I think each application needs to be independently authorized. It is likely your institution has already authorized abraunegg/onedrive. Here is the OAuth2 client ID if you want to try to get it authorized at your institution https://github.com/jstaf/onedriver/blob/master/fs/graph/oauth2.go#L22.
