### ISSUE TITLE
How to package a rpm for CentOS 7?

### ISSUE THREAD

**Issue by landall** [jstaf/onedriver#371]
There is no webkit2gtk-4.1(webkitgtk3-devel) but only webkitgtk3-devel.

What should I do to compile and package it in CentOS 7?

**Comment by jstaf** [comment]
A bunch of stuff doesn't work with the GUI app on CentOS 7/Ubuntu 18. Specifically, there are no "systemd user" sessions or services, so the GUI can't start mounts as your current user (it needs systemd user services to work). 

However, you can always compile and run the CLI `onedriver` app and that *does* work on any OS, no matter how old (it even works on mac) - just do `make onedriver` to compile that one, then you can `onedriver /path/to/some/mount` to mount the drive.
