### ISSUE TITLE
uninstall removes more packages than needed

### ISSUE THREAD

**Issue by Plarpoon** [jstaf/onedriver#374]
I have just experienced a really weird bug, I own a laptop and a desktop computer, both running Kubuntu 23.10. The laptop was a fresh distro install from this morning.

In both machines I have installed onedriver from the prebuilt DEB package as the repository installation was not possible (see issue #373 for why).

When I uninstalled the package on my laptop it removed an enormous amount of packages it should have never tagged.

> sudo apt autoremove onedriver
[sudo] password for plarpoon:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  alsa-base apport apport-kde apport-symptoms ark baloo-kf5 bluez-cups cdrdao cryptsetup cryptsetup-initramfs cups-pk-helper dc desktop-file-utils
  dolphin elisa ffmpeg ffmpegthumbs fonts-noto-color-emoji freerdp2-x11 geoip-database ghostscript-x gir1.2-atk-1.0 gir1.2-freedesktop
  gir1.2-gdkpixbuf-2.0 gir1.2-gtk-3.0 gir1.2-harfbuzz-0.0 gir1.2-notify-0.7 gir1.2-pango-1.0 gir1.2-udisks-2.0 gnupg-agent gnustep-base-common
  gnustep-base-runtime gnustep-common go-mtpfs gstreamer-qapt gstreamer1.0-pipewire gwenview haruna im-config inputattach kaccounts-integration
  kamera kate kate5-data kcalc kde-config-tablet kde-config-whoopsie kde-spectacle kdegraphics-thumbnailers kdenetwork-filesharing kerneloops
  kimageformat-plugins kio-audiocd kirigami-addons-data konversation konversation-data kpeople-vcard krdc ksystemlog ktorrent ktorrent-data
  kubuntu-notification-helper kubuntu-settings-desktop kubuntu-web-shortcuts kwin-wayland lame language-selector-common laptop-detect libao-common
  libao4 libaribb24-0 libavdevice60 libavif15 libcddb2 libcdio-cdda2 libcdio-paranoia2 libcdr-0.1-1 libcfitsio10 libchm1 libcolamd3 libcupsimage2
  libdolphinvcs5 libdvbpsi10 libebml5 libfakekey0 libflatpak0 libfreehand-0.1-1 libfreerdp-client2-2 libfreerdp2-2 libgav1-1 libgeoip1 libglu1-mesa
  libgnustep-base1.29 libixml11 libkcolorpicker0 libkf5baloowidgets-bin libkf5baloowidgets5 libkf5compactdisc5 libkf5contacts-data libkf5contacts5
  libkf5i18nlocaledata5 libkf5kdcraw5 libkf5plotting5 libkf5pulseaudioqt3 libkf5sane-data libkf5sane5 libkf5torrent6abi1 libkf5unitconversion-data
  libkf5unitconversion5 libkimageannotator-common libkimageannotator0 libksanecore1 libktorrent-l10n libkubuntu1 libkuserfeedbackwidgets1
  liblirc-client0 liblua5.2-0 libmalcontent-0-0 libmatroska7 libmpv2 libmspub-0.1-1 libmujs3 libnfs13 libntfs-3g89 libokular5core11
  libopenmpt-modplug1 libostree-1-1 libpagemaker-0.0-0 libpangoxft-1.0-0 libperl4-corelibs-perl libprotobuf-lite32 libproxy-tools libqapt3
  libqapt3-runtime libqt5quickparticles5 libqt5webkit5 libqt5xmlpatterns5 libraw23 libreoffice-calc libreoffice-draw libreoffice-impress
  libreoffice-kf5 libreoffice-plasma libreoffice-qt5 libreoffice-uiconfig-calc libreoffice-uiconfig-draw libreoffice-uiconfig-impress
  libresid-builder0c2a libsidplay2 libsignon-extension1 libsixel1 libsnapd-qt-2-1 libspatialaudio0 libspectre1 libspeexdsp1 libsuitesparseconfig7
  libupnp17 liburing2 libva-wayland2 libvisio-0.1-1 libvlc-bin libvlc5 libvlccore9 libvncclient1 libwhoopsie-preferences0 libwhoopsie0 libwinpr2-2
  libxatracker2 libxfont2 libxpresent1 libxvmc1 libyuv0 linux-sound-base lp-solve memtest86+ mscompress okular okular-extra-backends onedriver
  p11-kit p11-kit-modules p7zip p7zip-full pastebinit pavucontrol-qt pavucontrol-qt-l10n pcmciautils plasma-calendar-addons
  plasma-dataengines-addons plasma-distro-release-notifier plasma-runners-addons plasma-wallpapers-addons plasma-widgets-addons
  plasma-workspace-wayland plocate policykit-desktop-privileges ppa-purge print-manager printer-driver-brlaser printer-driver-c2esp
  printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-min12xxw printer-driver-pnm2ppa printer-driver-ptouch
  printer-driver-pxljr printer-driver-sag-gdi printer-driver-splix python3-apport python3-brotli python3-cairo python3-certifi python3-click
  python3-colorama python3-cups python3-cupshelpers python3-dbus.mainloop.pyqt5 python3-debconf python3-idna python3-mutagen python3-problem-report
  python3-pycryptodome python3-requests python3-systemd python3-urllib3 python3-websockets python3-xkit qapt-batch qapt-deb-installer
  qml-module-org-kde-kaccounts qml-module-org-kde-kirigami-addons-labs-mobileform qml-module-org-kde-people qml-module-qtquick-particles2
  qml-module-qtquick-xmllistmodel rfkill rtmpdump sddm sddm-theme-breeze signon-kwallet-extension signon-plugin-password signon-ui-service
  signon-ui-x11 signond skanlite spice-vdagent system-config-printer-common system-config-printer-udev tzdata-legacy ubuntu-drivers-common
  ubuntu-release-upgrader-qt unar unzip update-notifier-common usb-creator-common usb-creator-kde vlc-data vlc-plugin-base whoopsie
  whoopsie-preferences x11-apps x11-session-utils x11-xkb-utils xbitmaps xcvt xfonts-base xfonts-scalable xinit xinput xorg xserver-common
  xserver-xorg xserver-xorg-core xserver-xorg-input-all xserver-xorg-input-libinput xserver-xorg-input-wacom xserver-xorg-legacy
  xserver-xorg-video-all xserver-xorg-video-amdgpu xserver-xorg-video-ati xserver-xorg-video-fbdev xserver-xorg-video-intel
  xserver-xorg-video-nouveau xserver-xorg-video-qxl xserver-xorg-video-radeon xserver-xorg-video-vesa xserver-xorg-video-vmware xwayland yt-dlp zip
0 upgraded, 0 newly installed, 290 to remove and 0 not upgraded.
After this operation, 498 MB disk space will be freed.

So I tried again on my desktop computer and there it tagged the proper package list instead.

> sudo apt autoremove onedriver
[sudo] password for plarpoon:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  enchant-2 libenchant-2-2 libjavascriptcoregtk-4.0-18 libmanette-0.2-0 libwebkit2gtk-4.0-37 libwpe-1.0-1 libwpebackend-fdo-1.0-1 onedriver
0 upgraded, 0 newly installed, 8 to remove and 12 not upgraded.
After this operation, 118 MB disk space will be freed.
Do you want to continue? [Y/n]

Both applications have been installed using QApt Package Installer directly from the DEB file itself.

This is the only package this has ever happened to me, it could very well be a mistake on my end but if it isn't I would like to inform you.

**Comment by foopsss** [comment]
I don't use Debian based distributions, but this really looks like a bug on your end to me. onedriver clearly does not directly depend on things like KDE, LibreOffice or X11, and the [control file](https://github.com/jstaf/onedriver/blob/master/pkg/debian/control) is very clear about what the dependencies should be on Debian and Debian-based systems.

**Comment by Plarpoon** [comment]
Yeah, sorta guessed this was the case, still when in doubt I had decided to present it. Thank you for you feedback @foopsss!

**Comment by jstaf** [comment]
Yes, @foopsss is correct. `sudo apt autoremove` not only removes packages no longer needed by onedriver, but all the now-unneeded dependencies from all the other software you've previously uninstalled as well. If you run it without arguments (just `sudo apt autoremove` by itself), you'll see the same result.
