### ISSUE TITLE
OpenSUSE Repo

### ISSUE THREAD

**Issue by DavidAnniwell** [jstaf/onedriver#376]
README.md lists the OpenSUSE repo for Leap 15.3 but the repo is now for 15.4. The command to install the COPR repo should now read:
sudo zypper addrepo -g -r https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/opensuse-leap-15.4/jstaf-onedriver-opensuse-leap-15.4.repo onedriver

**Comment by foopsss** [comment]
Great, thanks for the reminder! It should be fixed with #377 as soon as jstaf is able to merge it.

**Comment by foopsss** [comment]
Fixed now as @jstaf has merged the relevant PR a couple of minutes now. This should be closed.
