### ISSUE TITLE
Setup on servers not documented

### ISSUE THREAD

**Issue by Fusseldieb** [jstaf/onedriver#381]
I've installed onedriver successfully on one of my Ubuntu Server's, but I can't really set up it without the "GUI". 

If I try nonetheless I get:
```
20:06:44 WRN Configuration file not found, using defaults. error="open /home/---/.config/onedriver/config.yml: no such file or directory" path=/home/---/.config/onedriver/config.yml
20:06:44 INF onedriver v0.14.1 15a1c642
Unable to init server: Could not connect: Verbindungsaufbau abgelehnt (Translation: "Connection rejected")

(onedriver:1383066): Gtk-WARNING **: 20:06:44.409: cannot open display:
```
Since it's not really documented how to proceed, I'm kinda lost.

**Comment by jstaf** [comment]
Did you check the man page or use `--help`? Anyhow, `onedriver --no-browser` is what you want.

**Comment by Fusseldieb** [comment]
Thanks for the response @jstaf 

However, I didn't even know that `--help` was an option to be honest.

It would be nice to have an explanation of the parameters in the README, especially for beginners that stumble upon `onedriver`.
