### ISSUE TITLE
gtk/gtk.h build error on SteamOS Arch

### ISSUE THREAD

**Issue by FuzzyExpress** [jstaf/onedriver#392]
When making onedriver on SteamOS Arch Linux on my SteamDeck
```cmake
# github.com/jstaf/onedriver/fs/graph
oauth2_gtk.c:1:10: fatal error: gtk/gtk.h: No such file or directory
    1 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:22: onedriver] Error 1
```
I tried both the AUR and build from source, same error.
```bash
 makepkg -is
 sudo pacman -S onedriver-0.14.1.tar.gz 
```
and 
```bash
git clone https://github.com/jstaf/onedriver
cd onedriver
make
```
I searched google for the error, both related to SteamOS Arch, one said to use the OneDrive for Linux client, the other was a different error, and I didn't see a fix.

Normally I would just use the OneDrive for Linux client, like I did on my laptop that died. But it won't fit on the deck. (I have too much stuff)

Edit: I did the cleaning on my OneDrive and Deck to make room for it. it is downloading the files. *it = OneDrive for Linux

**Comment by jstaf** [comment]
OneDrive for Linux is an entirely different program. Anyhow, to fix this one, you need the appropriate development headers, in this case GTK. I'm not an Arch Linux user but there is a maintainer who has a working package - you can install it from the AUR: https://aur.archlinux.org/packages/onedriver
