### ISSUE TITLE
The add account screen is blank now.

### ISSUE THREAD

**Issue by cercos** [jstaf/onedriver#398]
System info:
Operating System: Arch Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.9-arch1-2 (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen Threadripper PRO 5945WX 12-Cores
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA T1000 8GB/PCIe/SSE2
Manufacturer: LENOVO
Product Name: 30E000MEUS
System Version: ThinkStation P620

screenshot of the window that pops up when I click the +

![Screenshot_20240509_234603](https://github.com/jstaf/onedriver/assets/1372688/e17d2c95-aa52-44d2-b3c8-aebfa2ba44d5)

**Comment by foopsss** [comment]
Seems very similar to #378.

**Comment by cercos** [comment]
> Seems very similar to #378. Does this happen if you use Wayland?

No I'm using X but it is exactly that bug, didn't read the issue list thoroughly enough.

**Comment by cercos** [comment]
> Seems very similar to #378. Does this happen if you use Wayland?

Misread your question and just switched to wayland and it works in wayland so i guess that's a workaround for now but i cant use wayland very long because of nvidia issues.

**Comment by foopsss** [comment]
Yeah, I understand. I think some of the other users that reported this problem in the original issue may be using NVIDIA as well.

Could you leave a comment in the original issue with all the information you provided here and close this one? To avoid duplicates. Also, please tell us which driver you are using when this happens (Nouveau, proprietary, NVIDIA's open GPU modules).
