### ISSUE TITLE
Github Desktop

### ISSUE THREAD

**Issue by Tobias-Auer** [jstaf/onedriver#404]
Hi, I really like this application, but I think there is a big problem regarding GithubDesktop.

I used the option to add a repo to Github Desktop that is stored in Onedrive, but after that Onedriver dismounted my entire Onedrive folder and refused to remount it. (I toggled the switch but nothing happened and after reopening the GUI the toggle was off again)

After I killed the Github desktop process, I was able to mount it again.

Am I just stupid and missed something or is this really a bug with oneDriver or github desktop?

**Comment by Tobias-Auer** [comment]
d

**Comment by thennothinghappened** [comment]
This isn't exactly related to your issue but I do just wanna point out that Git and OneDrive do not mix. 

OneDrive gets very freaked out by the `.git` folder and sync errors will very often severely damage your repos. Given you're already using GitHub, just let the repos be somewhere else and all will be well :)
