### ISSUE TITLE
Create a donate option

### ISSUE THREAD

**Issue by aquaspy** [jstaf/onedriver#42]
Well, I read all onedrives projetcs for linux and your project is the best by far, but I can not recommend it to my friends until it have a gui. And as you are the only developer (I am a developer too, but I don't know to to help in this project), I though that would be cool to have a donation option, then me and the other people who can not help programming can at least pay a pizza or a coffee to you haha.

**Comment by jstaf** [comment]
Aw, thanks! Let me see what I can do re: creating a donate option.

**Comment by jstaf** [comment]
It took me awhile, but I now support donations via Github Sponsors - there is a "sponsor" button on the main repository page if you'd like to donate going forwards :slightly_smiling_face: 

Also you probably know about this, but onedriver also has a GUI now.
