### ISSUE TITLE
onedriver-headless in debian Sid

### ISSUE THREAD

**Issue by valeriob** [jstaf/onedriver#65]
Hi,
i'm trying to use onedriver-headless v0.8.0 into a debian:sid container
I'm able to login, but then i get this error, what am i missing ?

/tmp/onedriver-headless -d /mnt/OneDriveValerio/   

-- login dance --

INFO[2020-04-08T06:14:05]main.go:103 000001:main.main() onedriver v0.8.0 a895b066
FATA[2020-04-08T06:14:05]cache.go:45 000001:fs.NewCache() Could not open DB                             err="open /root/.cache/onedriver/onedriver.db: no such file or directory"

![image](https://user-images.githubusercontent.com/1522516/78752074-ada9ae80-7973-11ea-8652-e706a871f917.png)

Thanks

**Comment by jstaf** [comment]
It looks like you need to do `mkdir /root/.cache` first (I guess I assumed that directory would already exist, will have onedriver create it for the next release). 

You also need to expose the fuse kernel module on the host to the docker container. This is what I had to do to run onedriver in a fedora container just now:

```
$ docker run --cap-add SYS_ADMIN --device /dev/fuse -it fedora bash
[root@20bf5e7e7761 /]# dnf -y install wget fuse
[root@20bf5e7e7761 /]# wget https://github.com/jstaf/onedriver/releases/download/v0.8.0/onedriver-headless
[root@20bf5e7e7761 ~]# chmod +x onedriver-headless 
[root@20bf5e7e7761 ~]# mkdir .cache mount
[root@20bf5e7e7761 ~]# ./onedriver-headless mount/
```

**Comment by jstaf** [comment]
Ok, should be fixed in https://github.com/jstaf/onedriver/pull/66.

Don't forget to run containers with `--cap-add SYS_ADMIN --device /dev/fuse` and install `fuse` inside the container if you intend to use onedriver via Podman/Docker :wink:

**Comment by valeriob** [comment]
Thank you !

**Comment by valeriob** [comment]
I have a follow up question, i would like to use onedriver in a container inside unraid (right now i'm still testing on my pc).
I would like to spin up the container to run onedriver, then expose the onedrive filesystem to the host, is it possible ? i tried to mount a volume to :/mnt and i told onedriver to mount on /mnt/onedrive it does not look like working, do you have any advice? 

Thanks
Valerio

**Comment by jstaf** [comment]
Honestly this should work via exposing the onedriver mountpoint as a volume. I'd also make sure you're also mounting /root/.cache/onedriver in the container to the host as well (that's where onedriver's disk cache and auth tokens are stored - you'd want these on the host if you want the data to persist between container restarts). 

Generally speaking, anything that works for running sshfs in a container should work for onedriver (sshfs is a more-widely known filesystem that mounts a filesystem over SSH, but is functionally identical to onedriver in terms of how it is setup and run via FUSE).
