### ISSUE TITLE
Sometimes some images gets corrupted

### ISSUE THREAD

**Issue by drom98** [jstaf/onedriver#77]
Yesterday I've uploaded a folder with some wallpapers in it, today, when I opened that folder I've noticed some files are corrupted.
This is a normal file:
![image](https://user-images.githubusercontent.com/19615827/80912442-cddf4a00-8d34-11ea-8032-6a8c71c9f841.png)
This is a corrupted file (look at the size and at the file format):
![image](https://user-images.githubusercontent.com/19615827/80912460-ef403600-8d34-11ea-91fe-bab6b2900fb8.png)

While I was writing this up, I've noticed a bunch of corrupted files I've lost on another folder.
![image](https://user-images.githubusercontent.com/19615827/80912493-34fcfe80-8d35-11ea-81b0-b54b0cabd546.png)

I don't know the cause of the problem.

My system: 
![image](https://user-images.githubusercontent.com/19615827/80912501-47773800-8d35-11ea-8d9c-0f2d1f311288.png)

**Comment by jstaf** [comment]
So the first time a file gets created / added to onedrive, onedriver uploads an empty "placeholder" file to obtain an ID from the server. The file content then gets uploaded in a follow-up request. If this follow-up upload fails, you'd be left with only the original empty placeholder file. I'm guessing this is related to the same issue as in #74 (file uploads not succeeding).

**Comment by jstaf** [comment]
To help debug this a little further, you can get the log for onedriver via:

```
journalctl --user -u onedriver@-home-drom-OneDrive
```

I am particularly interested in any lines with "Error during small file upload" as part of the log entry.

**Comment by drom98** [comment]
> ```
> journalctl --user -u onedriver@-home-drom-OneDrive
> ```

`No journal files were found.
-- No entries --
`

**Comment by jstaf** [comment]
This should now be solved in version 0.9.0, but if not, please reopen this issue and let me know.
