### ISSUE TITLE
0 bytes file

### ISSUE THREAD

**Issue by dipunm** [jstaf/onedriver#89]
I am using an encrypted keepass file on onedrive. Recently, I have noticed that when saving from the program, the file is shown correctly on my local disk, but in OneDrive, it shows as 0 bytes and does not seem to ever update.

I am not sure what exactly could be causing this, but I do know that the software will write to a tmp file (blahj930d.tmp) and then overwrite the original file using a rename operation.

This may be a recent bug since I have been using this for a while and only recently had this problem (and I recently re-installed). I'm happy to run any tests to help diagnose further.

Hopefully you have some idea of what might be happening.

PS. I am using keepassxc to manage the file
onedriver v0.9.0 fe22e1d6

**Comment by jstaf** [comment]
Hi @dipunm I think this was a bug carried from versions before 0.9.x (an unsuccessful upload could lead to this state). To fix:

* Copy the keepass file out of the OneDrive mount
* Delete the copy of the keepass file in the OneDrive folder
* Copy the keepass file back into its original folder

This should force it to re-upload the file correctly. Also I recommend upgrading to 0.9.1, as that has some additional bugfixes that are useful for stuff like libreoffice and filenames with symbols in the name.
